### ISSUE TITLE
Remove .pyc files from the code folder

### ISSUE THREAD

**Issue by anew-bhav** [divija96/Emotion-Detection#4]
The .pyc files are not required to be included in the code folder, once main.py runs, they are automatically generated. 

These files can be included in the .gitignore file using *.pyc

**Comment by divija96** [comment]
The .pyc files have been removed. Thanks for bringing this to notice.

**Comment by anew-bhav** [comment]
I was in process of making my commit for this issue, but you did it before. @divija96 
 You just deleted the .pyc files but i think these files will be generated again when the python script runs again. in the pull request which I made, i have included a gitignore file which will ignore all .pyc files . I think you should , merge this pull request.
